---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# RMPSH

<!-- badges: start -->
<!-- badges: end -->

The goal of RMPSH is to ...

## Installation

You can install the development version of RMPSH from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("priyamdas2/RMPS")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(RMPSH)
## basic example code

g <- function(y)
return(-20 * exp(-0.2 * sqrt(0.5 * (y[1] ^ 2 + y[2] ^ 2)))
 - exp(0.5 * (cos(2 * pi * y[1]) + cos(2 * pi * y[2])))
 + exp(1) + 20)

par0 <- rep(1,10)
g(par0)
solution <- RMPSH_opt(par0,g, rep(-33,10), rep(33,10))
g(solution)

# Will print the updates after each iteration
RMPSH_opt(c(2,4,6,2,1),g,rep(-3,5), rep(23,5), verbose = 1)

# Will exit and return result after 2 seconds
g <- function(y) { return(sum(y^2)) }
RMPSH_opt(rep(2.3,100),g, rep(-11,100), rep(13,100), max_time = 2, verbose = 0)
```
